before_script:
  - npm install -g eslint
  - npm install -g grunt-cli
language: node_js
node_js:
  - "0.11"
  - "0.10"
services: redis
after_script: istanbul cover ./node_modules/mocha/bin/_mocha --report lcovonly -- -R spec && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
