language: node_js
node_js:
  - 4
  - 6.9.1
  - 6
  - 7.6.0
  - 7
  - node
services: redis
# this runs eslint, runs the tests, instruments their coverage, and
# publishes it to coveralls.io
script: npm run ci
after_script:
  - redis-cli script flush

# Don't build pushes to branches other than master. This doesnâ€™t affect pull-
# request builds, which are separate from branch builds in Travis.
branches:
  only:
    - master
