version: 1
update_configs:
  - package_manager: 'javascript'
    directory: '/'
    update_schedule: 'live'
    version_requirement_updates: 'widen_ranges'
    commit_message:
      prefix: 'chore'
      include_scope: true
